# Generated by Django 5.0.6 on 2024-05-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_remove_customer_cus_id_remove_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Thanhtien',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
