# Generated by Django 5.0.6 on 2024-05-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_order_thanhtien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=True, max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=True, max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
