# Generated by Django 5.0.6 on 2024-05-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_remove_customer_id_remove_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='code',
        ),
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
