# Generated by Django 5.0.6 on 2024-05-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_rename_customer_id_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=True, max_length=8, primary_key=True, serialize=False),
        ),
    ]
