# Generated by Django 5.0.6 on 2024-05-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_order_from_customer_order_line_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_line',
            name='order_code',
        ),
    ]
