# Generated by Django 5.0.6 on 2024-05-15 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_remove_order_line_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_line',
            name='order_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record.order_from_customer'),
        ),
    ]
