# Generated by Django 5.0.6 on 2024-05-17 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_order_line_order_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_From_Customer',
            new_name='OrderFromCustomer',
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.IntegerField()),
                ('thanh_tien', models.DecimalField(decimal_places=0, max_digits=6)),
                ('order_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record.orderfromcustomer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Order_Line',
        ),
    ]
