# Generated by Django 5.0.6 on 2024-05-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_alter_product_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.CharField(max_length=50),
        ),
    ]
