# Generated by Django 5.0.6 on 2024-05-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0014_alter_product_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='thanh_tien',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(),
        ),
    ]
