# Generated by Django 5.0.6 on 2024-05-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0015_remove_orderline_thanh_tien_alter_product_unit_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderFromCustomer',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cus_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='order_code',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='sl',
            new_name='so_luong',
        ),
    ]
