# Generated by Django 5.0.6 on 2024-05-18 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_rename_orderfromcustomer_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='so_luong',
            new_name='quantity',
        ),
    ]
