# Generated by Django 5.0.6 on 2024-05-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0017_rename_so_luong_orderline_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
