# Generated by Django 5.0.6 on 2024-06-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0020_alter_customer_code_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
