# Generated by Django 5.0.6 on 2024-06-18 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0021_alter_order_order_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSegments',
            fields=[
                ('seg_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('seg_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='record.category'),
        ),
        migrations.AddField(
            model_name='customer',
            name='seg',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='record.customersegments'),
        ),
    ]
